name: "CI Tests"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        ruby: ["2.6"]
        rails: ["5.2", "6.0", "master"]

    env:
      RAILS_VERSION: "${{ matrix.rails }}"

    services:
      postgres:
        image: "postgres:11.5"
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: "actions/checkout@v1"

    - name: "Install Ruby ${{ matrix.ruby }}"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: "Generate lockfile"
      run: |
        bundle config path vendor/bundle
        bundle lock

    - name: "Cache dependencies"
      uses: "actions/cache@v1"
      with:
        path: "vendor/bundle"
        key: bundle-${{ hashFiles('Gemfile.lock') }}

    - name: "Install dependent libraries"
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: "Run Setup"
      env:
        PGHOST: "localhost"
        PGUSER: "postgres"
        RAILS_ENV: "test"
      run: |
        bin/setup

    - name: "Run Tests"
      env:
        PGHOST: "localhost"
        PGUSER: "postgres"
        RAILS_ENV: "test"
      run: |
        bin/rails test
